### ISSUE TITLE
Недостаток digi спрайтов на 01/13/24

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#1752]
У корвакса есть такая заповедь.
Сделай что-то и не поддерживай больше никогда в жизни нахуй.

- [x] Clothing/Shoes/Boots/highheelboots.rsi/ #2252
- [x] Clothing/Shoes/Boots/magboots-science.rsi/ #1719 
- [x] Clothing/Shoes/Boots/speedboots.rsi/ #2252
- [x] Clothing/Shoes/Boots/winterboots.rsi/ и другие версии  #2252
- [x] Clothing/Shoes/Misc/snakeskin.rsi/ #2252
- [x] Clothing/Shoes/Specific/clown_banana.rsi/ #2252
- [x] Clothing/Shoes/Specific/skates.rsi/ #2252
- [x] Clothing/Under/Socks/ #2252
- [x] Clothing/Uniforms/Jumpsuit/ce_turtle.rsi/ #2252
- [x] Clothing/Uniforms/Jumpsuit/centcom_agent.rsi/ #2252
- [x] Clothing/Uniforms/Jumpsuit/clown_banana.rsi/ #2252
- [x] Clothing/Uniforms/Jumpsuit/curator.rsi/ #2252
- [x] Clothing/Uniforms/Jumpsuit/familiar_garbs.rsi/ #2252
- [x] Clothing/Uniforms/Jumpsuit/loungewear.rsi/ #2252
- [x] Clothing/Uniforms/Jumpsuit/ninja.rsi/ #2252
- [x] Clothing/Uniforms/Jumpsuit/qmturtle.rsi/ #2252
- [x] Clothing/Uniforms/Jumpsuit/web.rsi/ #2252
